#  入门

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)
x = torch.randn_like(x, dtype=torch.float)    # 重载 dtype!
print(x)                                      # 结果size一致

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.9771, -1.5464,  0.7365],
        [ 0.2894,  2.2332,  0.6639],
        [ 1.1960, -1.0653,  1.4924],
        [-1.8203, -1.4601, -0.1597],
        [-0.9878,  1.9973,  1.0760]])


In [6]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.2353, -1.1532,  0.9649],
        [ 0.6667,  2.7005,  1.2753],
        [ 1.2556, -0.5069,  1.9082],
        [-0.9452, -1.2304, -0.1401],
        [-0.4976,  2.6822,  2.0283]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3260, 0.4049, 0.7490],
        [0.0215, 0.6240, 0.4427],
        [0.3461, 0.0348, 0.3176],
        [0.6668, 0.4628, 0.2952],
        [0.5183, 0.8008, 0.7875]])


In [7]:
print(torch.add(x, y))

tensor([[ 1.2353, -1.1532,  0.9649],
        [ 0.6667,  2.7005,  1.2753],
        [ 1.2556, -0.5069,  1.9082],
        [-0.9452, -1.2304, -0.1401],
        [-0.4976,  2.6822,  2.0283]])


In [8]:
torch.cuda.is_available()

True

In [9]:
## 当GPU可用时,我们可以运行以下代码
## 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

tensor([[ 1.9771, -0.5464,  1.7365],
        [ 1.2894,  3.2332,  1.6639],
        [ 2.1960, -0.0653,  2.4924],
        [-0.8203, -0.4601,  0.8403],
        [ 0.0122,  2.9973,  2.0760]], device='cuda:0')
tensor([[ 1.9771, -0.5464,  1.7365],
        [ 1.2894,  3.2332,  1.6639],
        [ 2.1960, -0.0653,  2.4924],
        [-0.8203, -0.4601,  0.8403],
        [ 0.0122,  2.9973,  2.0760]], dtype=torch.float64)


In [13]:
import time
import torch

# 测试gpu计算耗时
A = torch.ones(5000, 5000).to('cuda')
B = torch.ones(5000, 5000).to('cuda')
startTime2 = time.time()
for i in range(101):
    C = torch.matmul(A, B)
endTime2 = time.time()
print('gpu计算总时长:', round((endTime2 - startTime2) * 1000, 2), 'ms')

# 测试cpu计算耗时
A = torch.ones(5000, 5000)
B = torch.ones(5000, 5000)
startTime1 = time.time()
for i in range(1):
    C = torch.matmul(A, B)
endTime1 = time.time()
print('cpu计算总时长:', round((endTime1 - startTime1) * 1000, 2), 'ms')
 

gpu计算总时长: 13.96 ms
cpu计算总时长: 2086.49 ms
